[package]
name = "lay-wayland"
version = "0.1.0"
edition = "2021"

[lints.rust]
dead_code = "allow"
unused_imports = "allow"

[dependencies]
log    = {workspace = true}
libc   = {workspace = true}
mio    = {workspace = true}
rustix = {workspace = true}
